name: checkbox-openvino-ai-plugins-gimp
summary: Checkbox tests for the openvino-ai-plugins-gimp snap
description: |
  Collection of tests for the OpenVINO AI Plugins for GIMP
version: '1.0.0'
confinement: classic
grade: stable

base: core24

# Here are the available applications of the checkbox provider for the OpenVINO AI Plugins for GIMP snap
# To run : snap run checkbox-openvino-ai-plugins-gimp.<app>
#
# checkbox-cli:
#   - checkbox client, can be used to talk to the checkbox daemon
# remote-slave:
#   - checkbox slave daemon that will the responsible for running the test sesssion
#     in the remote fashion (through checkbox-cli)
# shell:
#   - give shell access to the provider snap
# test-runner / test-runner-automated:
#   - execute all provider tests inside the snap environment
#     the test execution is standalone and does not depend on the remote-slave daemon
# install-full-deps:
#   - install all depedencies needed for provider jobs
apps:
  checkbox-cli:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper
  remote-slave:
    command-chain: [bin/wrapper_local]
    command: bin/checkbox-cli-wrapper slave
    daemon: simple
    restart-condition: always
  shell:
    command-chain: [bin/wrapper_local]
    command: bin/shell-wrapper
  test-runner:
    command-chain: [bin/wrapper_local]
    command: bin/test-runner
  test-runner-automated:
    command-chain: [bin/wrapper_local]
    command: bin/test-runner-automated
  install-full-deps:
    command: bin/install-full-deps

parts:
  checkbox-provider-openvino-ai-plugins-gimp:
    plugin: dump
    source: ./checkbox-provider-openvino-ai-plugins-gimp
    source-type: local
    build-snaps:
      - checkbox-provider-tools
      - checkbox24
    build-attributes:
      - enable-patchelf
      # See: https://snapcraft.io/docs/linters-classic
      # This patches the python interpreter to allow use of the dynamic linker from core24
    stage-packages:
      - jq
      - intel-gpu-tools
      - python3-minimal
      - python3.12-minimal
      # This provides a python interpreter for checkbox to use that works properly with classic confinement
    override-build: |
      for path in $(find "/snap/checkbox24/current/providers/" -mindepth 1 -maxdepth 1 -type d); do export PROVIDERPATH=$path${PROVIDERPATH:+:$PROVIDERPATH}; done
      checkbox-provider-tools validate
      checkbox-provider-tools build
      checkbox-provider-tools install --layout=relocatable --prefix=/providers/checkbox-provider-openvino-ai-plugins-gimp --root="$SNAPCRAFT_PART_INSTALL"

  bin:
    plugin: dump
    source: bin
    organize:
      '*': bin/
