name: openvino-ai-plugins-gimp
base: core24
summary: Intel's OpenVINO™ AI Plugins for GIMP
description: |
  OpenVINO™ AI plugins for GIMP adds AI functionality to GIMP for
  stable diffusion, super resolution, and semantic segmentation.
  The plugins can run on Intel CPU, NPU, or GPU devices. This snap
  also provides an application for downloading models that can be
  used with the stable diffusion plugin.

grade: stable
confinement: strict
adopt-info: gimp-plugins

platforms:
  amd64:

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl:
    bind: $SNAP/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl

package-repositories:
  - type: apt
    ppa: kobuk-team/intel-graphics
    key-id: 0C0E6AF955CE463C03FC51574D098D70AFBE5E1F

# the recommended mountpoint for the content is /openvino-ai-plugins-gimp
slots:
  openvino-ai-plugins-gimp-libs:
    interface: content
    content: openvino-ai-plugins-gimp-2404
    read:
      - /

plugs:
  intel-npu:
    interface: custom-device
    custom-device: intel-npu-device
  npu-libs:
    interface: content
    content: npu-libs-2404
    target: $SNAP/npu-libs
  openvino-libs:
    interface: content
    content: openvino-libs-2404
    target: $SNAP/openvino
  dot-local-share-openvino-ai-plugins-gimp:
    interface: personal-files
    write:
      - $HOME/.local/share/openvino-ai-plugins-gimp

apps:
  model-setup:
    command-chain: ["command-chain/openvino-launch", "command-chain/openvino-ai-plugins-gimp-launch"]
    command: usr/bin/python3 $SNAP/model_setup.py
    plugs:
      - dot-local-share-openvino-ai-plugins-gimp # models stored in home directory
      - opengl # Intel GPU access (device nodes)
      - intel-npu # Intel NPU access (device node)
      - npu-libs # Intel NPU access (libs)
      - network # for downloading models
      - openvino-libs # OpenVINO runtime
    environment:
      LD_LIBRARY_PATH: $SNAP/npu-libs:$LD_LIBRARY_PATH
      PYTHONPATH: $SNAP/lib/python3.12/site-packages:$PYTHONPATH
      OCL_ICD_VENDORS: $SNAP/etc/OpenCL/vendors

parts:
  gimp-plugins:
    source-type: git
    source: https://github.com/intel/openvino-ai-plugins-gimp
    source-tag: 3.1.2
    plugin: python
    python-requirements:
      - ./requirements.txt
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --abbrev=4 --always)"
    override-build: |
      craftctl default
      mkdir -p ${CRAFT_PART_INSTALL}/weights ${CRAFT_PART_INSTALL}/gimp-plugins
      cp -r weights/* ${CRAFT_PART_INSTALL}/weights/
      cp model_setup.py ${CRAFT_PART_INSTALL}
      cp -r gimpopenvino/plugins/* ${CRAFT_PART_INSTALL}/gimp-plugins/
      # plugins set plugin version from git tags, so copy repo metadata into snap
      cp -r .git ${CRAFT_PART_INSTALL}/gimp-plugins/
      chmod +x ${CRAFT_PART_INSTALL}/gimp-plugins/stable_diffusion_ov/stable_diffusion_ov.py
      chmod +x ${CRAFT_PART_INSTALL}/gimp-plugins/semseg_ov/semseg_ov.py
      chmod +x ${CRAFT_PART_INSTALL}/gimp-plugins/superresolution_ov/superresolution_ov.py
    build-environment:
      - PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
    stage-packages:
      - python3-minimal # python interpreter
      - python3.12-minimal # python interpreter
      - libva2 # openvino gpu plugin dep
      - libgl1 # opencv-python dep
      - libglu1-mesa # opencv-python dep
      - libxcb1 # opencv-python dep
      - libice6 # opencv-python dep
      - libsm6 # opencv-python dep
      - libx11-6 # opencv-python dep
      - libxext6 # opencv-python dep
      - libgomp1 # pytorch dep
      - git # plugin version displayed in GIMP by running "git describe"
    stage:
      - -lib/python3.12/site-packages/torch/lib/libtorchbind_test.so
      # TODO: build openvino-genai from source, linking against
      #       openvino-toolkit-2404 in latest/edge (2025.2.0)
      #- -lib/python3.12/site-packages/openvino
      #- -lib/python3.12/site-packages/openvino_telemetry
      - -usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
      - -usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libicuio.so.74.2
      - -usr/lib/x86_64-linux-gnu/libicutest.so.74.2
      - -usr/lib/x86_64-linux-gnu/libvulkan.so.1.3.275
      - -usr/lib/x86_64-linux-gnu/libOpenGL.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
      - -usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libicutu.so.74.2
      - -usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-randr.so.0.1.0
      - -usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libicui18n.so.74.2

  intel-graphics:
    plugin: nil
    stage-packages:
      - libigc-dev
      - libigc-tools
      - libigc2
      - libigdfcl-dev
      - libigdfcl2
      - intel-ocloc
      - intel-ocloc-dev
      - intel-opencl-icd
      - libze1
      - libze-dev
      - libze-intel-gpu-dev
      - libze-intel-gpu1
      - libigdgmm12
      - libigdgmm-dev

  command-chain-openvino:
    plugin: dump
    source-type: git
    source: https://github.com/canonical/openvino-toolkit-snap.git
    source-tag: 2025.2.0-amd64-rev30
    stage:
      - command-chain/openvino-launch

  command-chain-openvino-ai-plugins-gimp:
    plugin: dump
    source: command-chain/
    organize:
      '*': command-chain/

lint:
  ignore:
    - library:
      # These are needed but are flagged
      # by the linter because they are not
      # explicitly linked to any binary or
      # shared object
      - openvino/usr/runtime/3rdparty/tbb/lib/libtbbbind*
      - openvino/usr/runtime/3rdparty/tbb/lib/libtbbmalloc*
      - openvino/usr/runtime/3rdparty/tbb/lib/libhwloc*
      - usr/lib/x86_64-linux-gnu/libva.so.*
      - usr/lib/x86_64-linux-gnu/libze_intel_gpu.so.*
      - usr/local/lib/libiga64.so*
      - usr/local/lib/libigc.so.*
      - usr/local/lib/libigdfcl.so.*
      - usr/local/lib/libopencl-clang*
      - lib/python3.12/site-packages/torch/lib/libtorch_global_deps.so
