name: openvino-ai-plugins-gimp
base: core24
summary: Intel's OpenVINO™ AI Plugins for GIMP
description: |
  OpenVINO™ AI plugins for GIMP adds AI functionality to GIMP for
  stable diffusion, super resolution, and semantic segmentation.
  The plugins can run on Intel CPU, NPU, or GPU devices. This snap
  also provides an application for downloading models that can be
  used with the stable diffusion plugin.

grade: stable
confinement: strict
adopt-info: gimp-plugins

platforms:
  amd64:

layout:
  /usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl:
    bind: $SNAP/openvino-gimp/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/intel-opencl
  /etc/gitconfig:
    bind-file: $SNAP_DATA/etc/gitconfig

package-repositories:
  - type: apt
    ppa: kobuk-team/intel-graphics
    key-id: 0C0E6AF955CE463C03FC51574D098D70AFBE5E1F

slots:
  gimp-plugins:
    interface: content
    content: gimp-plugins
    source:
      read:
        - $SNAP/semseg_ov
        - $SNAP/stable_diffusion_ov
        - $SNAP/superresolution_ov
        - $SNAP/openvino_utils
        - $SNAP/openvino-gimp
        - $SNAP/wrappers-openvino-gimp

plugs:
  intel-npu:
    interface: custom-device
    custom-device: intel-npu-device
  npu-libs:
    interface: content
    content: npu-libs-2404
    target: $SNAP/npu-libs

apps:
  model-setup:
    command-chain: ["command-chain/source-content-producers"]
    command: openvino-gimp/usr/bin/python3 $SNAP/openvino-gimp/model_setup.py
    plugs:
      - opengl # Intel GPU access (device nodes)
      - intel-npu # Intel NPU access (device node)
      - npu-libs # Intel NPU access (libs)
      - network # for downloading models

parts:
  gimp-plugins:
    source-type: git
    source: https://github.com/intel/openvino-ai-plugins-gimp
    source-tag: 3.1.2
    plugin: python
    python-requirements:
      - ./requirements.txt
    override-pull: |
      craftctl default
      # remove dependencies mounted from openvino-toolkit-2404 content producer snap
      sed -i '/\"openvino\"/d' ./setup.py
      sed -i '/\"numpy\"/d' ./setup.py
      sed -i '/openvino/d' ./requirements.txt
      craftctl set version="$(git describe --tags --abbrev=4 --always)"
      git apply ${CRAFT_PROJECT_DIR}/patches/001-optimum-cli-from-path.patch
    override-build: |
      craftctl default
      mkdir -p ${CRAFT_PART_INSTALL}/weights
      cp -r weights/* ${CRAFT_PART_INSTALL}/weights/
      cp model_setup.py ${CRAFT_PART_INSTALL}
      cp -r gimpopenvino/plugins/* ${CRAFT_PART_INSTALL}
      rm ${CRAFT_PART_INSTALL}/__init__.py
      # plugins set plugin version from git tags, so copy repo metadata into snap
      cp -r .git ${CRAFT_PART_INSTALL}/openvino_utils/
      chmod +x ${CRAFT_PART_INSTALL}/stable_diffusion_ov/stable_diffusion_ov.py
      chmod +x ${CRAFT_PART_INSTALL}/semseg_ov/semseg_ov.py
      chmod +x ${CRAFT_PART_INSTALL}/superresolution_ov/superresolution_ov.py
    build-environment:
      - PIP_EXTRA_INDEX_URL: https://download.pytorch.org/whl/cpu
    stage-packages:
      - python3-minimal # python interpreter
      - python3.12-minimal # python interpreter
      - libva2 # openvino gpu plugin dep
      - libgl1 # opencv-python dep
      - libglu1-mesa # opencv-python dep
      - libxcb1 # opencv-python dep
      - libice6 # opencv-python dep
      - libsm6 # opencv-python dep
      - libx11-6 # opencv-python dep
      - libxext6 # opencv-python dep
      - libgomp1 # pytorch dep
      - git # plugin version displayed in GIMP by running "git describe"
    stage-snaps:
      - openvino-toolkit-2404/2025/stable
    stage:
      - -lib/python3.12/site-packages/torch/lib/libtorchbind_test.so
      - -usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
      - -usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libicuio.so.74.2
      - -usr/lib/x86_64-linux-gnu/libicutest.so.74.2
      - -usr/lib/x86_64-linux-gnu/libvulkan.so.1.3.275
      - -usr/lib/x86_64-linux-gnu/libOpenGL.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
      - -usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libicutu.so.74.2
      - -usr/lib/x86_64-linux-gnu/libxcb-dri2.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-present.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-randr.so.0.1.0
      - -usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0.0.0
      - -usr/lib/x86_64-linux-gnu/libxshmfence.so.1.0.0
      - -usr/lib/x86_64-linux-gnu/libicui18n.so.74.2
    organize:
      bin: openvino-gimp/bin
      etc: openvino-gimp/etc
      include: openvino-gimp/include
      lib: openvino-gimp/lib
      lib64: openvino-gimp/lib64
      model_setup.py: openvino-gimp/model_setup.py
      share: openvino-gimp/share
      usr: openvino-gimp/usr
      var: openvino-gimp/var
      weights: openvino-gimp/weights

  intel-graphics:
    plugin: nil
    override-build: |
      craftctl default
      # update paths to the Intel Installable Client Drivers (ICDs) for OpenCL
      intel_icd="${CRAFT_PART_INSTALL}"/etc/OpenCL/vendors/intel.icd
      intel_icd_so_path=$(cat ${intel_icd})
      base_path="/snap/${SNAPCRAFT_PROJECT_NAME}/current/openvino-gimp"
      echo "${base_path}""${intel_icd_so_path}" > "${intel_icd}"
      intel_legacy1_icd="${CRAFT_PART_INSTALL}"/etc/OpenCL/vendors/intel_legacy1.icd
      if [ -f ${intel_legacy1_icd} ]; then
        intel_legacy1_icd_so_path=$(cat ${intel_legacy1_icd})
        echo "${base_path}""${intel_legacy1_icd_so_path}" > "${intel_legacy1_icd}"
      fi
    stage-packages:
      - libigc-dev
      - libigc-tools
      - libigc2
      - libigdfcl-dev
      - libigdfcl2
      - intel-ocloc
      - intel-ocloc-dev
      - intel-opencl-icd
      - libze1
      - libze-dev
      - libze-intel-gpu-dev
      - libze-intel-gpu1
      - libigdgmm12
      - libigdgmm-dev
    organize:
      bin: openvino-gimp/bin
      etc: openvino-gimp/etc
      include: openvino-gimp/include
      lib: openvino-gimp/usr/lib
      share: openvino-gimp/share
      usr: openvino-gimp/usr

  command-chain-openvino-ai-plugins-gimp:
    plugin: dump
    source: command-chain/
    organize:
      source-content-producers: command-chain/source-content-producers
      openvino-ai-plugins-gimp.env: wrappers-openvino-gimp/openvino-ai-plugins-gimp.env

lint:
  ignore:
    - library:
      # These are needed but are flagged
      # by the linter because they are not
      # explicitly linked to any binary or
      # shared object
      - openvino-gimp/lib/python3.12/site-packages/torch/*
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libGLU.so.1.3.1
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libGLX_mesa.so.0.0.0
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libOpenCL.so.1.0.0
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libicuio.so.74.2
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libicutest.so.74.2
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libiga64.so.2.16.0+0
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libigc.so.2.16.0+0
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libigdfcl.so.2.16.0+0
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libva.so.2.2200.0
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libvulkan.so.1.3.275
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libz3.so.4
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libze_intel_gpu.so.1.6.34666
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libze_loader.so.1.23.1
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libze_tracing_layer.so.1.23.1
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libze_validation_layer.so.1.23.1
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libOpenGL.so.0.0.0
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libXxf86vm.so.1.0.0
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libicutu.so.74.2
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libopencl-clang.so.15
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
      - openvino-gimp/usr/lib/x86_64-linux-gnu/libicui18n.so.74.2
